/**
 * PPTX creation skill content for the document_generate upskill action.
 *
 * This is a compact Entropic sandbox reference adapted from public PptGenJS
 * and presentation-generation guidance. It is not executable code.
 */

export function getPptxFreeformSkill(): string {
  return `# PPTX Creation Skill - Entropic Sandbox Reference

## 1. Execution model

Your code runs inside a sandboxed Node VM with PptGenJS helpers.
- Return a PptGenJS presentation object from \`pptx()\` or \`new pptxgenjs()\`.
- You may also return \`{ presentation, fileName }\`.
- Available data: \`context.entity\`, \`context.initiatives\`, \`context.matrix\`, \`context.workspace\`.
- Timeout: 30 seconds for code execution.
- No \`require\`, \`import\`, \`fs\`, \`fetch\`, \`process\`, network, or template import/editing.
- Use inches for coordinates. Wide slides are 13.333 x 7.5 inches.

## 2. Recommended workflow

1. Create a presentation with \`const deck = pptx({ title: "..." })\`.
2. Add a title slide and section slides before dense content.
3. Build each slide with explicit \`x\`, \`y\`, \`w\`, and \`h\` values.
4. Prefer visual structure: tables, callouts, comparisons, timelines, and placeholders.
5. Return \`deck\` only after all slides are added.

## 3. Helpers available

| Helper | Purpose |
| --- | --- |
| \`pptx(opts?)\` | Presentation with wide layout, default fonts, metadata |
| \`titleSlide(deck, title, subtitle?, opts?)\` | Cover slide |
| \`sectionSlide(deck, title, subtitle?, opts?)\` | Section divider |
| \`textBox(slide, text, opts)\` | Stable text box with shrink fit |
| \`bullets(slide, items, opts)\` | Bullet list using PowerPoint bullets |
| \`table(slide, headers, rows, opts)\` | Table with styled header and borders |
| \`statCallout(slide, label, value, opts)\` | Metric/callout card |
| \`footer(slide, text, opts?)\` | Small footer text |
| \`visualPlaceholder(slide, label, opts)\` | Explicit image/diagram placeholder |
| \`safeText(value, fallback?)\` | Defensive text coercion |

Raw \`pptxgenjs\` is also available for advanced PptGenJS APIs.

## 4. Layout rules

- Always use explicit coordinates. Do not rely on implicit placement.
- Keep text inside boxes; set \`fit: "shrink"\` when text length is uncertain.
- Use 0.6-0.8 inch outside margins on most slides.
- Titles usually fit in y=0.45..1.0, content starts around y=1.25.
- Body font sizes: 14-18 pt. Captions: 8-11 pt. Titles: 26-36 pt.
- Avoid text-only decks. Every slide should have a visible structure.
- Use a restrained palette: dark text, one accent, light fills.
- Do not fake bullets with characters; use \`bullets()\` or PptGenJS bullet options.
- Do not include external images or remote assets in BR-21a.

## 5. Complete example

\`\`\`javascript
const deck = pptx({ title: context.entity.name || "Generated presentation" });

titleSlide(deck, context.entity.name || "Generated presentation", context.entity.description);

sectionSlide(deck, "Portfolio overview", "Current initiatives and expected value");
let slide = deck.addSlide();
textBox(slide, "Initiatives", {
  x: 0.7, y: 0.45, w: 7.5, h: 0.45, fontSize: 26, bold: true
});
table(
  slide,
  ["Name", "Status", "Summary"],
  (context.initiatives || []).slice(0, 6).map((item) => [
    item.data?.name || "Untitled",
    item.status || "n/a",
    item.data?.description || ""
  ]),
  { x: 0.7, y: 1.25, w: 8.4, fontSize: 10.5 }
);
statCallout(slide, "Initiatives", String((context.initiatives || []).length), {
  x: 9.55, y: 1.25, w: 2.7
});
visualPlaceholder(slide, "Add a workflow or matrix visual", {
  x: 9.55, y: 2.9, w: 2.7, h: 2.1
});
footer(slide, "Generated by Entropic");

return deck;
\`\`\`
`;
}
