import vm from 'node:vm';
import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';
import pptxgenjs from 'pptxgenjs';
import {
  bullets,
  footer,
  getSandboxGlobals,
  pptx,
  resolvePptxGenJSConstructor,
  safeText,
  sectionSlide,
  statCallout,
  table,
  textBox,
  titleSlide,
  type PptxFreeformContext,
  visualPlaceholder,
} from '../../src/services/pptx-freeform-helpers';
import {
  executeFreeformPptxCode,
  isPptxPresentation,
  writePptxBuffer,
} from '../../src/services/pptx-generation';
import { getPptxFreeformSkill } from '../../src/services/pptx-freeform-skill';

const stubContext: PptxFreeformContext = {
  entity: { id: 'folder-1', name: 'Test Folder', description: 'A test presentation' },
  initiatives: [
    { id: 'init-1', status: 'completed', data: { name: 'Initiative 1', description: 'First' } },
    { id: 'init-2', status: 'draft', data: { name: 'Initiative 2', description: 'Second' } },
  ],
  matrix: null,
  workspace: { id: 'workspace-1' },
};

describe('pptx-freeform helpers', () => {
  it('should create a PptGenJS presentation with defaults', () => {
    const deck = pptx({ title: 'Deck title' });
    expect(deck).toBeInstanceOf(pptxgenjs);
    expect(deck.layout).toBe('LAYOUT_WIDE');
    expect(deck.title).toBe('Deck title');
  });

  it('should build a valid PPTX buffer with helper slides and objects', async () => {
    const deck = pptx({ title: 'Helper deck' });
    titleSlide(deck, 'Helper deck', 'Generated by unit tests');
    sectionSlide(deck, 'Section', 'A compact divider');
    const slide = deck.addSlide();
    textBox(slide, 'Overview', { x: 0.7, y: 0.45, w: 6, h: 0.4, fontSize: 24, bold: true });
    bullets(slide, ['First point', 'Second point'], { x: 0.8, y: 1.2, w: 4.8, h: 1.2 });
    table(slide, ['Name', 'Status'], [['Initiative 1', 'Done']], { x: 0.8, y: 2.65, w: 5.3 });
    statCallout(slide, 'Total initiatives', '2', { x: 7, y: 1.2, w: 3 });
    visualPlaceholder(slide, 'Workflow diagram', { x: 7, y: 3, w: 3, h: 1.6 });
    footer(slide, 'Generated by Entropic');

    const buffer = await writePptxBuffer(deck);
    expect(buffer.byteLength).toBeGreaterThan(0);
    expect(buffer[0]).toBe(0x50);
    expect(buffer[1]).toBe(0x4b);
  });

  it('should accept a valid presentation created from a different pptxgenjs module instance', () => {
    const require = createRequire(import.meta.url);
    const cjsPptxGenJS = require('pptxgenjs') as typeof pptxgenjs;
    const deck = new cjsPptxGenJS();

    expect(deck).not.toBeInstanceOf(pptxgenjs);
    expect(isPptxPresentation(deck)).toBe(true);
  });

  it('should resolve a constructible pptxgenjs class from nested default exports', () => {
    class FakePptxGenJS {
      addSlide() {
        return {
          addText() {},
          addShape() {},
          addTable() {},
          background: undefined,
        };
      }

      async write() {
        return Buffer.from('PK');
      }
    }

    expect(resolvePptxGenJSConstructor({ default: { default: FakePptxGenJS } })).toBe(
      FakePptxGenJS,
    );
  });

  it('should expose sandbox helpers and hide Node runtime globals', () => {
    const globals = getSandboxGlobals(stubContext);
    expect(typeof globals.pptx).toBe('function');
    expect(typeof globals.titleSlide).toBe('function');
    expect(typeof globals.sectionSlide).toBe('function');
    expect(typeof globals.textBox).toBe('function');
    expect(typeof globals.bullets).toBe('function');
    expect(typeof globals.table).toBe('function');
    expect(typeof globals.statCallout).toBe('function');
    expect(typeof globals.footer).toBe('function');
    expect(typeof globals.visualPlaceholder).toBe('function');
    expect(globals.pptxgenjs).toBe(pptxgenjs);

    const sandbox = vm.createContext(globals);
    const result = new vm.Script(
      '(function() { return [typeof process, typeof require, context.entity.name].join(":") })()',
    ).runInContext(sandbox, { timeout: 5000 });
    expect(result).toBe('undefined:undefined:Test Folder');
  });

  it('should execute sandbox code and return a presentation', async () => {
    const result = executeFreeformPptxCode(
      `
      const deck = pptx({ title: context.entity.name });
      titleSlide(deck, context.entity.name, context.entity.description);
      const slide = deck.addSlide();
      table(slide, ["Name", "Status"], context.initiatives.map((item) => [
        item.data?.name || "Untitled",
        item.status || "n/a"
      ]));
      return deck;
      `,
      stubContext,
    );

    expect(isPptxPresentation(result.presentation)).toBe(true);
    const buffer = await writePptxBuffer(result.presentation);
    expect(buffer.byteLength).toBeGreaterThan(0);
  });

  it('should accept an approved wrapper result with fileName', () => {
    const result = executeFreeformPptxCode(
      `
      const presentation = pptx({ title: "Wrapped" });
      titleSlide(presentation, "Wrapped");
      return { presentation, fileName: "wrapped-deck.pptx" };
      `,
      stubContext,
    );
    expect(result.fileName).toBe('wrapped-deck.pptx');
    expect(isPptxPresentation(result.presentation)).toBe(true);
  });

  it('should reject invalid return values with a stable error code', () => {
    expect(() => executeFreeformPptxCode('return { ok: true };', stubContext)).toThrow(
      /invalid_return_type/,
    );
    try {
      executeFreeformPptxCode('return { ok: true };', stubContext);
    } catch (error) {
      expect((error as { code?: string }).code).toBe('invalid_return_type');
    }
  });

  it('should map syntax errors to code_syntax_error', () => {
    try {
      executeFreeformPptxCode('return pptx({ title: ;', stubContext);
    } catch (error) {
      expect((error as { code?: string }).code).toBe('code_syntax_error');
    }
  });

  it('should provide defensive text coercion', () => {
    expect(safeText(null, 'fallback')).toBe('fallback');
    expect(safeText('  spaced\ntext  ')).toBe('spaced text');
  });

  it('should return compact upskill guidance', () => {
    const skill = getPptxFreeformSkill();
    expect(skill.length).toBeGreaterThan(500);
    expect(skill).toContain('PptGenJS');
    expect(skill).toContain('pptx()');
    expect(skill).toContain('Wide slides are 13.333 x 7.5 inches');
    expect(skill).toContain('No `require`, `import`, `fs`, `fetch`, `process`');
  });
});
